### ISSUE TITLE
npm module contains unnecessary dependencies 

### ISSUE THREAD

**Issue by evanmoran** [kmalakoff/backbone-modelref#2]
I'm looking at using this with Node and it appears your npm package.json file includes modules for testing / minimizing that aren't used in modelref. Would it be possible to separate out this build related stuff so the dependences stay small in the 'backbone-modelref' module? All good if not, I can work around it. It would just be helpful=).

Thanks for the thoughtful project!

**Comment by kmalakoff** [comment]
@evanmoran Hello! Yes, I realize it is a bit heavy. 

Basically, I've been working on automating packing using easy-bake (https://github.com/kmalakoff/easy-bake) so that I can make sure that all of my tests run with the latest versions since I'm now using TravisCI and want to catch problems as close to when they are introduced as possible. 

For nuget, I've been creating a separate minimal project with only the library files. It is a bit time consuming to maintain (managing 2 and now 3 projects for each version!), but I suppose that is what is needed. I'll add it to my todo list and will see if I can automate this somehow.

**Comment by evanmoran** [comment]
I understand the challenge. I'm writing a web framework called SMITE and it currently has several npm modules to keep things configurable. I'm not even done with it and it already is a pain to keep everything published correctly=). No rush on working on this, I just thought I'd mention that I ran into it.

**Comment by kmalakoff** [comment]
No worries. I've just finished with an re-published on npm. There are dependencies on underscore and backbone, but no building and testing scripts anymore!
